[package]
name = "non_none_fields"
version = "0.1.0"
authors = ["the DIGR authors"]
edition = "2018"

[dependencies]
syn = { version = "1.0.33", features = ["full", "parsing", "extra-traits"] }
quote = "1.0.7"

[lib]
proc-macro = true
